controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'testByName'
        permanent: true
        name: 'Michel' 

# index:
#     path: /
#     controller: App\Controller\DefaultController::index

# toto:
#     path: /toto
#     controller: App\Controller\DefaultController::chemin


